name: compile pdf and create release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: index.tex
          latexmk_shell_escape: true

      - name: create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: upload pdf
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./index.pdf
          asset_name: index.pdf
          asset_content_type: pdf
